### ISSUE TITLE
[KK-FEATURE]수정 페이지 작업

### ISSUE THREAD

**Issue by rkrua** [nbcamp-archive/kkuk-ios#102]
## Description

- 팬모달 띄워주기
- 수정하기 작동
- 수정페이지 작동

## Tasks

- [x] panmodal 만들고 이식하기
- [x] 팬모달을 통해 수정,삭제하기
- [x] 렐름 데이터베이스 수정하기
- [x] 수정페이지 진입시 아이디에 맞는 아이콘과 이름 보여주기
- [x] 수정시 이너뷰에서 이름 바뀌게 하기
