### ISSUE TITLE
[KK-DESIGN]카테고리 생성 페이지 및 정보페이지 수정 

### ISSUE THREAD

**Issue by Sonyeongha** [nbcamp-archive/kkuk-ios#115]
## Description

-  카테고리 생성 페이지 와 정보 페이지 수정 

## Tasks
- [ ] 카테고리 아이콘 스위치문을 이넘으로 바꾸기 
- [ ] 정보페이지 시스템 설정 탭 하면 휴내폰 내부 설정으로 들어가는 것 (복사하기 붙여넣기, 오픈소스내용)
- [ ] 정보 페이지 (개인정보 정책 삭제, 간격줄이기, 
- [ ] 화면 구조 수정
