### ISSUE TITLE
[KK-DESIGN] 검색 화면 top view 추가

### ISSUE THREAD

**Issue by jooYeonStudyiOS** [nbcamp-archive/kkuk-ios#118]
## Description

- 카테고리, 검색, 설정 화면 top view 추가
- Top View 추가에 따른 다른 화면들 오토레이아웃 수정
- 다크 모드에도 자연스럽게 보일수 있도록 수정

## Tasks

- [x] 카테고리 화면 top view 추가
- [x] 검색 화면 top view 추가
- [x] 설정 화면 top view 추가
- [x] 카테고리, 검색, 설정 테이블뷰 다크모드 설정
