### ISSUE TITLE
[KK-FEATURE] 오픈소스 라이선스 표기

### ISSUE THREAD

**Issue by yujinkim1** [nbcamp-archive/kkuk-ios#126]
## Description

- 시스템 설정에서 애플리케이션에 적용된 오픈소스의 라이선스를 표기하는 설정을 추가합니다.

## Tasks

- [ ] License plist 파일 추출
- [ ] 설정 화면에 기타 설정 화면으로 적용
- [ ] 사용하지 않은 패키지 의존성 제거
