### ISSUE TITLE
[KK-FEATURE] 정보페이지 모든데이터지우는 기능 구현 

### ISSUE THREAD

**Issue by Sonyeongha** [nbcamp-archive/kkuk-ios#136]
## Description

- 모든데이터 삭제 realm data base의 데이터를 지우는 것 

## Tasks

- [x] 모든데이터 삭제 realm data base의 데이터를 지우는 것 
- [x] 미분류 카테고리 모달 화면 버튼 히든처리
- [ ] 카테고리 삭제시 콘텐츠도 삭제되도록 처리
