### ISSUE TITLE
[KK-DESIGN] 디자인 오류 수정

### ISSUE THREAD

**Issue by jooYeonStudyiOS** [nbcamp-archive/kkuk-ios#140]
## Description

- 화면 별로 통일되지 않은 부분 통일시키는 작업

## Tasks

- [ ] 홈화면 타이틀 하얀색 고정
- [ ] 홈화면 즐겨찾기 cell의 선 겹치는 부분 수정
- [ ] 카테고리 화면 양 여백 맞추기
- [ ] 카테고리 추가 화면 아이콘 여백 맞추기
- [ ] 카테고리, 검색, 설정 화면에서 topview 와의 간격 통일
- [ ] 검색화면 검색창 tap했을 때 배경색 변경

**Comment by jooYeonStudyiOS** [comment]
동일한 alert 함수 사용 
- WebView 중에 텍스트 필드 사용하는 부분에서는 공통 함수 미사용
- 설정 화면에서 모든 데이터 지우기 부분도 작업중에 있어 수정하지 않음 -> 추후 수정할 필요성 있음
