### ISSUE TITLE
[KK-FEATURE] 홈 화면 즐겨찾기, pageControl 기능 수정 

### ISSUE THREAD

**Issue by se-ryeong** [nbcamp-archive/kkuk-ios#165]
## Description

- 홈 화면 즐겨찾기, pageControl 기능 수정하기

## Tasks

- [x] 즐겨찾기 5개 이상 추가 시 alert띄워주기
- [x] pin고정 5개이상 안되게 수정하기
- [x] pageControl로 이동 못하게 수정하기
