### ISSUE TITLE
[KK-DESIGN] AppTabBarController 탭바 아이템 설정

### ISSUE THREAD

**Issue by yujinkim1** [nbcamp-archive/kkuk-ios#30]
## Description

- 시스템 디스플레이 설정에 따라 사용하는 탭바 아이템 아이콘을 변경합니다.

## Tasks

- [x] 홈 탭바 아이템
- [x] 카테고리 탭바 아이템
- [x] 검색 탭바 아이템
- [x] 설정 탭바 아이템

**Comment by yujinkim1** [comment]
`UITabBarController`의 `UITabBarItem` 객체는 비트맵 이미지(`.png`, `.jpg`)를 사용하기 때문에 .png로 변경해야할 것으로 보인다.
