### ISSUE TITLE
[KK-DESIGN] 최근 검색어 view와 컨텐츠 tableview 표시 순서 변경 

### ISSUE THREAD

**Issue by jooYeonStudyiOS** [nbcamp-archive/kkuk-ios#33]
## Description

(10/23일 기능 회의) 
변경 전 
- 컨텐츠 tableview 표시 후 검색창 tap 하면 최근 검색어 view 표시

변경 후
- 최근 검색어 view 표시 후 검색창에서 검색어를 입력해서 검색하면 컨텐츠 tableview 표시
- 표시 순서의 변경으로 인해 cancel 버튼 불필요해저 삭제
- cancel 버튼의 작업을 SearchBar의 cancel으로 대체

## Tasks

- [x] 최근 검색어 view와 컨텐츠 tableview 표시 순서 변경 
- [x] cancel 버튼 삭제
- [x] clear 버튼이 cancel 버튼을 대체
