### ISSUE TITLE
[KK-FEATURE] 최근 검색어 관리

### ISSUE THREAD

**Issue by jooYeonStudyiOS** [nbcamp-archive/kkuk-ios#35]
## Description

- UserDefaults를 이용하여 최근 검색어 관리 CRD

## Tasks

- [x] UserDefaults에 최근 검색어 저장하기(저장은 10개까지만)
- [x] UserDefaults에서 최근 검색어 불러오기 & label에 설정하기
- [x] UserDefaults에서 선택 된 최근 검색어 1개 삭제하기
- [x] UserDefaults에서 최근 검색어 전체 삭제하기
- [x] 저장, 삭제 등에 따른 화면 갱신 및 cell 갱신
