### ISSUE TITLE
[KK-DESIGN] 콘텐츠 추가 화면 수정

### ISSUE THREAD

**Issue by yujinkim1** [nbcamp-archive/kkuk-ios#73]
## Description

- 필수 입력이 아닌 사용자가 선택적으로 입력하지 않아도 되는 내용에 대한 표시 라벨을 추가합니다.

## Tasks

- [x] Optional 라벨 추가
- [x] 카테고리 선택 화면 레이아웃 수정 
- [x] AddContentButton 제거
- [x] 카테고리 추가 화면 구조 수정
- #74
