### ISSUE TITLE
[KK-DESIGN] 홈화면 디자인 수정

### ISSUE THREAD

**Issue by se-ryeong** [nbcamp-archive/kkuk-ios#75]
## Description

- 홈화면 디자인 수정하기.

## Tasks

- [x] 최근 보관한 항목 -> 최근 보관한 콘텐츠로 수정
- [x] Recommend View에 pin 추가
- [x] empty 에셋 크기 수정
- [x] Recommend View 크기 수정
- [x] topFrameView 길이 수정
