### ISSUE TITLE
[KK-DESIGN] 검색화면 디자인 변경

### ISSUE THREAD

**Issue by jooYeonStudyiOS** [nbcamp-archive/kkuk-ios#78]
## Description

(10월 31일 회의 피드백 반영)
- 검색화면 디자인 변경

## Tasks

- [x] 검색창 디자인 변경 - 테두리색 넣기 등
- [x] x 아이콘 작게 변경
- [x] 전체삭제 글씨 색 변경
- [x] 검색창 양 옆 여백 맞추기
- [x] 네이게이션 타이틀 "검색" 설정
