### ISSUE TITLE
[KK-FEATURE] 검색 화면 기능 개선

### ISSUE THREAD

**Issue by jooYeonStudyiOS** [nbcamp-archive/kkuk-ios#80]
## Description

- 검색 화면 기능 추가

## Tasks

- [x] 최근 검색어 정렬 순서 변경 → 최근 검색한 내용이 앞으로 오도록 변경하기
- [x] 검색어 입력 시 메모 에서도 검색하여 표시하기
- [x] 대문자, 소문자 구분 없이 검색하기
- [x]  화면 사라질 때 내용 초기화해서 탭바 이동 시 초기화하기
- [x] 키보드 내리기
