### ISSUE TITLE
[KK-FEATURE] 홈화면 수정

### ISSUE THREAD

**Issue by se-ryeong** [nbcamp-archive/kkuk-ios#85]
## Description

- 홈 화면 기능 수정

## Tasks

- [x] RecommendView pin버튼 클릭시 상단에서 삭제 및 cell pin버튼 선택안됨처리
- [x] floating button 위치 조절
- [x] RecommendView 이미지 AspectFill로 수정
