### ISSUE TITLE
[KK-FEATURE] 홈 화면 기능 수정

### ISSUE THREAD

**Issue by se-ryeong** [nbcamp-archive/kkuk-ios#87]
## Description

- 홈 화면 기능 수정

## Tasks

- [x] 스크롤 인디케이터 히든 처리
- [x] 핀 버튼 눌렀을 때 해당 아이템만 업데이트 되도록 하기
- [x] 즐겨찾기 콘텐츠 제목 높이값 문제 해결하기
