### ISSUE TITLE
[KK-DESIGN] ContentCell 개선

### ISSUE THREAD

**Issue by jooYeonStudyiOS** [nbcamp-archive/kkuk-ios#89]
## Description

- ContentCell 개선
- 그에 따른 TableView 수정

## Tasks

- [x] ContentCell 오토레이아웃 에러 수정 및 위치 수정
- [x] ImageView border 색깔 조정
- [x] more Button 추가
- [x] 그에 따른 TableView 수정 (홈, 카테고리, 검색 화면) (#92)
