### ISSUE TITLE
[KK-FEATURE] 카테고리 추가 화면 리디렉션 버튼

### ISSUE THREAD

**Issue by yujinkim1** [nbcamp-archive/kkuk-ios#90]
## Description

- 콘텐츠를 추가 화면에서도 카테고리를 만들 수 있도록 카테고리 추가하기 버튼을 추가합니다.

## Tasks

- [x] 카테고리 추가하기 리디렉션 버튼 이미지 에셋
- [x] 카테고리 추가하기 리디렉션 버튼 추가 
- [x] 풀스크린 모달 화면에서의 화면 이동
