### ISSUE TITLE
[KK-DESIGN] 카테고리 추가 페이지 수정 

### ISSUE THREAD

**Issue by Sonyeongha** [nbcamp-archive/kkuk-ios#91]
## Description

카테고리 추가 페이지 피드백위주로 수정 

## Tasks

- [x] 아이콘 10개 추가하기
- [x] 화면이 나타났을 때 키보드 포커싱 되는거 해제
- [x] 네비게이션 바 카테고리 이름 입력하기 라벨 간격 (40)
- [x] 완료 → 카테고리가 성공적으로 저장되면 알럿 뷰
