### ISSUE TITLE
[KK-DESIGN] 검색화면 디자인 에러 해결 및 수정 사항 반영

### ISSUE THREAD

**Issue by jooYeonStudyiOS** [nbcamp-archive/kkuk-ios#99]
## Description

- 검색화면 디자인 에러 해결 및 수정 사항 반영

## Tasks

- [x] 최근 검색어 길어질 경우 ...표시
- [x] 검색창 높이를 다른 화면과 똑같게 맞추기
- [x] 아카아브가 없습니다 라벨 수정
- [x] 오토레이아웃 조금씩 조정
